fieldLayouts:
  5dc84cfa-1c81-4323-9833-fba5b78e3d13:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: ligging
name: Ligging
siteSettings:
  6de046f0-6167-4af1-aa91-ffaf83e36a14: # NL
    hasUrls: false
    template: null
    uriFormat: null
  e57cf13b-f9cb-484a-8093-a897fa43eb68: # EN
    hasUrls: false
    template: null
    uriFormat: null
  fd2014b7-5bc0-49a9-ac30-e009081532f7: # FR
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 418f2ca8-a38d-4d5c-8ec1-2c5760370c4b
